### ISSUE TITLE
No need to restart dwm on theme change

### ISSUE THREAD

**Issue by karlivory** [junnunkarim/dotfiles-linux#1]
You can bind call the xrdb reload key combination using e.g. xdotool

`
xdotool key "Shift+Super_L+F5"
`

No need to change dwm-flexipatch source code, only config.

**Comment by junnunkarim** [comment]
Hello @karlivory
I use the xrdb patch to change colorschemes in dwm.
 I get the colors from a file named ```theme``` and I have separate files for different colorschemes. I use a script to let the user choose a theme. After that, the script copies the selected theme's colorscheme file to the ```theme``` file and reloads dwm. That's how my theme_changer script works.

So I am unable to understand why I should bind the xrdb reload key combination using xdotool. Can you please elaborate?

**Comment by karlivory** [comment]
Sorry, I just realized my post contained very little information :)

I am talking about the line
https://github.com/junnunkarim/dotfiles-linux/blob/96e92e83357d199125857593e1637c707799c68f/.bin/theme_changer#L42

Reloading dwm messes up the window orders and brings everything to the first tag, which is disruptive to the user in my opinion. You can instead reload the colorscheme using the xrdb function provided by XRDB_PATCH

https://github.com/junnunkarim/dotfiles-linux/blob/96e92e83357d199125857593e1637c707799c68f/.config/dwm/config.def.h#L1161

which is instant and doesn't affect window placement at all. xdotool can be used to call that key combination within the theme_changer script. Alternatively you can call the xrdb function using the very useful FSIGNAL_PATCH and xsetroot (no key combination needed then).

**Comment by junnunkarim** [comment]
@karlivory 
Sorry for the late reply.
I tried reloading the colorscheme with xrdb function after manually changing the colorscheme but it doesn't seem to do anything.
Shouldn't it change the colorscheme by calling it after changing the theme file?

**Comment by karlivory** [comment]
@junnunkarim 
I made a PR that should be a working solution. I also moved the luastatus out of dwm/config.def.h to .xsession so it can be restarted separately of dwm

**Comment by junnunkarim** [comment]
fixed with #2
