### ISSUE TITLE
Package the wallpapers for the AUR

### ISSUE THREAD

**Issue by amtoine** [junnunkarim/dotfiles-linux#4]
Hi @junnunkarim :wave: :yum: 

i like your wallpapers a lot :eyes:

would you mind if i write a `PKGBUILD` to install them as a package on my ArchLinux installation? :star_struck: 

anyways cheers :wave: :tada:

**Comment by junnunkarim** [comment]
Hello there, @amtoine 

I collected these wallpapers from various sources and none of these wallpapers are not created by me.
So I won't mind at all if you write a PKGBUILD for your arch installation.
But If you create a package for the wallpapers and you upload it on your git repo, then I think you should mention the name of the original artists in the credit. Or else you might face people complaining that you are redistributing arts without permission just like I faced them.

Have a great day.

**Comment by amtoine** [comment]
@junnunkarim

> I collected these wallpapers from various sources and none of these wallpapers are not created by me.
> So I won't mind at all if you write a PKGBUILD for your arch installation.
> 
i see, that's great :relieved: 

> But If you create a package for the wallpapers and you upload it on your git repo, then I think you should mention the name of the original artists in the credit. Or else you might face people complaining that you are redistributing arts without permission just like I faced them.
> 
yep, i see you have a [README](https://github.com/junnunkarim/dotfiles-linux/blob/main/.config/wallpaper/README.md) with the credits to the authors :thumbsup: 
i can include that for sure :wink: 

i'll probably isolate them in a repo of mine, very likely `amtoine/junnunkarim-wallpapers`, then package them in something like `junnunkarim-wallpapers-git` and watch your `junnunkarim/dotfiles-linux` to be sure i do not miss an update on the wallpapers :muscle:
