### ISSUE TITLE
Nerd font not working

### ISSUE THREAD

**Issue by the-merky** [junnunkarim/dotfiles-linux#6]
Hi! I installed your config on Arch linux, carefully following the installation steps. I noticed however that the nerd font was missing. The icons on the bar and in rofi show up as squares. I reinstalled both of the font packages and attempted to recompile dwm which failed. I then rebooted my system. The problem is still there. Anything that could be causing this issue? Thanks :)

**Comment by the-merky** [comment]
My dwm compile error when using `sudo make install`: `cp: not replacing '/usr/local/share/xsession/dwm.desktop'`

**Comment by junnunkarim** [comment]
@ShambuKumar Sorry about that. Nerd Fonts recently renamed many their icons and I forgot to change them in my configs. Which is why you could only see squares instead of the respective icon.
I have updated the icons now.
Try it out now, it should work perfectly.

**Comment by the-merky** [comment]
Dear @junnunkarim  thank you for quick response, the issue appears to be resolved!
